#!/usr/bin/env python
#
# Sketch
#
# (c) 2012 Fetal-Neonatal Neuroimaging & Developmental Science Center
#                   Boston Children's Hospital
#
#              http://childrenshospital.org/FNNDSC/
#                        dev@babyMRI.org
#
# based on https://github.com/mudcube/Sketch.js
#

# import the plugin.py superclass
import os, sys
sys.path.append(os.path.join(os.path.dirname(__file__), '../'))
from plugin import Plugin

import datetime as d

class Sketch(Plugin):
  '''
  '''
  Plugin.AUTHORS = 'FNNDSC (dev@babyMRI.org) based on https://github.com/daleharvey/pacman work'
  Plugin.TITLE = 'Sketch'
  Plugin.CATEGORY = 'Others'
  Plugin.DESCRIPTION = 'An interactive Sketch plugin'
  Plugin.DOCUMENTATION = 'http://wiki'
  Plugin.LICENSE = 'Opensource (MIT)'
  Plugin.VERSION = '0.2'

  def run(self, options):
          print 'No CLI actions, I am a pure interactive plugin'
      

        
# ENTRYPOINT
if __name__ == "__main__":
  plugin = Sketch()
  
  # this is an interactive plugin
  plugin.interactive = True
  
  # define the parameters
  plugin.launch(sys.argv)
